# action.yml
name: "Goodreads books list scraper"
description: "Scrapes goodreads to get a given list of books from a given user and saves the json"
author: "Marco Bacis"
inputs:
  user:
    description: "Goodreads user id"
    required: true
  shelf:
    description: "Goodreads shelf, in snake case"
    required: true
  output_path:
    description: "Path to the output file to write"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.user }}
    - ${{ inputs.shelf }}
    - ${{ inputs.output_path }}